export const unv = [
  {
    id: 1,
    name: "الجامعة العربية الدولية (AIU).",
    fields: ["it", "", "arch", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 2,
    name: "جامعة الأندلس للعلوم الطبية.",
    fields: ["it", "civil", "", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 3,
    name: "الجامعة السورية الخاصة (SPU).",
    fields: ["it", "civil", "medicine", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 4,
    name: "جامعة القلمون الخاصة.",
    fields: ["it", "medicine", "arch", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 5,
    name: "الجامعة الدولية الخاصة للعلوم والتكنولوجيا.",
    fields: ["", "civil", "", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 6,
    name: "المعهد الفرنسي للشرق الأدنى.",
    fields: [""],
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 7,
    name: "جامعة الجزيرة الخاصة (JPU).",
    fields: ["it", "", "arch", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 8,
    name: "جامعة الشام الخاصة.",
    fields: ["it", "", "arch", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 9,
    name: "جامعة المنارة.",
    fields: ["it", "", "arch", "1"],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 10,
    name: "الجامعة الوطنية الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 11,
    name: "جامعة الحواش الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 12,
    name: "جامعة الوادي الدولية.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 13,
    name: "أكاديمية العلوم الصحية.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 14,
    name: "المعهد العالي لإدارة الأعمال (HIPA).",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 15,
    name: "جامعة اليرموك الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 16,
    name: "جامعة الاتحاد الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 17,
    name: "جامعة أنطاكية السورية الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 18,
    name: "الأكاديمية السورية الدولية للتدريب والتطوير.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 19,
    name: "جامعة روجافا.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 20,
    name: "المعهد الوطني للإدارة العامة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 21,
    name: "الجامعة الدولية للعلوم والنهضة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 22,
    name: "جامعة إبلا الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 23,
    name: "جامعة قرطبة الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 24,
    name: "الجامعة العربية للعلوم والتكنولوجيا.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 25,
    name: "جامعة قاسيون الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 26,
    name: "جامعة الرشيد الخاصة للعلوم والتكنولوجيا.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 27,
    name: "جامعة بلاد الشام.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 28,
    name: "جامعة الشهباء الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: 29,
    name: "جامعة الشمال الخاصة.",
    fields: [""],

    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
];

//  {
//   id: "1",
//   name: "الجامعة العربية الدولية (AIU)",
//fields: [""];
//
// address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
// {
//   id: "2",
//   name: "جامعة الأندلس للعلوم الطبية",
//   address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
// {
//   id: "3",
//   name: "الجامعة السورية الخاصة (SPU)",
//   address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
// {
//   id: "4",
//   name: "الجامعة العربية الخاصة",
//   address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
// {
//   id: "5",
//   name: "الجامعة العربية الخاصة",
//   address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
// {
//   id: "6",
//   name: "الجامعة العربية الخاصة",
//   address: "درعا",
//   phone: "05011111111",
//   email: "<EMAIL>",
//   website: "www.unv.edu.eg",
//   facebook: "www.facebook.com",
//   instagram: "www.instagram.com",
// },
