export const unv = [
  {
    id: "1",
    name: "جامعة اليرموك الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: "2",
    name: "الجامعة العربية الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: "3",
    name: "الجامعة العربية الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: "4",
    name: "الجامعة العربية الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: "5",
    name: "الجامعة العربية الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
  {
    id: "6",
    name: "الجامعة العربية الخاصة",
    address: "درعا",
    phone: "05011111111",
    email: "<EMAIL>",
    website: "www.unv.edu.eg",
    facebook: "www.facebook.com",
    instagram: "www.instagram.com",
  },
];
