export const team = [
  {
    id: 1,
    name: "محمد حسن الخليل تدمري",
    imageHref: "/images/hsn about.jpg",
    about: "Computer and automation Engineer  ",
    phone: "+963 997 391 745",
    email: "Mhdhasan.alkhalil@gmail.com",
    facebook: "https://www.facebook.com/mhammad.tadmori/",
    telegram: "https://t.me/HasnTD",
    linkedIn: "https://www.linkedin.com/in/mhd-hasan-tadmori/",
    github: "https://github.com/MHD-HSN-TD",
  },
  {
    id: 1,
    name: "محمد يحيى سبيني",
    about: "Software Engineere",
    imageHref: "/images/yehia about.jpg",
    phone: "0991176122",
    email: "yahyasbini@gmail.com",
    facebook: "https://www.facebook.com/profile.php?id=100026186868626",
    telegram: "https://www.linkedin.com/in/yahya-sbini-a2b10a213/",
    linkedIn: "https://t.me/yahyasbini",
    github: "",
  },
];
