export const team = [
  {
    id: 1,
    name: "محمد حسن الخليل تدمري",
    imageHref: "/images/hsn about.jpg",
    about: "مهندس حواسيب واتمتمة ",
    phone: "+963 997 391 745",
    email: "Mhdhasan.alkhalil@gmail.com",
    facebook: "https://www.facebook.com/mhammad.tadmori/",
    telegram: "https://t.me/HasnTD",
    linkedIn: "https://www.linkedin.com/in/mhd-hasan-tadmori/",
    github: "https://github.com/MHD-HSN-TD",
  },
  {
    id: 1,
    name: "يحيى السبيني",
    about: "مهندس حواسيب واتمتمة ",
    imageHref: "/images/yehia about.jpg",
    phone: "05011111111",
    email: "test@gmail.com",
    facebook: "www.facebook.com",
    telegram: "https://t.me/HasnTD",
    linkedIn: "https://www.linkedin.com/in/mhd-hasan-tadmori/",
    github: "https://github.com/MHD-HSN-TD",
  },
];
