import './globals.css'
import { Alexandria } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import NavBar from '@/components/navBar/NavBar'
import { Providers } from '@/components/Provider/Provider'


const alexandria = Alexandria({ subsets: ['arabic'], weight: ['300'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${alexandria.className} bg-default transition-all duration-300`}>
        <Providers>
          <NavBar />
          {children}
          {/* <div className='h-screen'>
          </div> */}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
